apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netdevice-and-l3
  name: netdevice-and-l3
  namespace: multi-network
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: netdevice-and-l3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: netdevice-and-l3
        k8s-app: netdevice-and-l3
      annotations:
        networking.gke.io/default-interface: 'eth0'
        networking.gke.io/interfaces: |
          [
            {
              "interfaceName": "eth0",
              "network": "default"
            },
            {
              "interfaceName": "eth1",
              "network": "netdevice-network"
            },
            {
              "interfaceName": "eth2",
              "network": "l3-network"
            }
          ]
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - image: busybox
        command:
        - sleep
        - "100000"
        imagePullPolicy: Always
        name: bb
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        cloud.google.com/gke-nodepool: device
