apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: regular-network
  name: regular-network
  namespace: multi-network
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: regular-network
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: regular-network
        k8s-app: regular-network
    spec:
      containers:
      - image: busybox
        command:
        - sleep
        - "100000"
        imagePullPolicy: Always
        name: busybox
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
