# https://cloud.google.com/kubernetes-engine/docs/how-to/setup-multinetwork-support-for-pods
---
apiVersion: networking.gke.io/v1
kind: Network
metadata:
  name: netdevice-network
spec:
  type: "Device"
  parametersRef:
    group: networking.gke.io
    kind: GKENetworkParamSet
    name: "netdevice"
