apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: hubble-metrics
  namespace: kube-system
  labels:
    k8s-app: hubble-relay
spec:
  selector:
    matchLabels:
      k8s-app: hubble-relay
  endpoints:
  - port: metrics
    interval: 30s
